server:
  port: 2020

spring:
  profiles:
    active: application.yml
  freemarker:
    suffix: .ftl
    cache: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ohm_subsystem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: ohms
    password: 123456
  servlet:
    multipart:
      max-file-size: 10485760
  mvc:
    static-path-pattern: /static/**
  cache:
    cache-names: common,system,user
    couchbase:
      expiration: 18000
  transaction:
    rollback-on-commit-failure: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    open-in-view: true
    database: mysql
  application:
    name: ohms-subsystem

# 日志配置
logging:
  config: classpath:configure/logger.xml
  file:
    path: logs
    name: log.txt
    max-size: 30MB
    max-history: 30
    clean-history-on-start: true
  pattern:
    rolling-file-name: log-%d{yyyyMMdd}.txt
